variables:
- group: "Azure"

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - api

pool:
  vmImage: ubuntu-latest

jobs:
- job: CI
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: 'api/src/*.csproj'
      nobuild: true
      arguments: '--configuration Release'
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'api/src/bin/Release/net9.0/publish.zip'
      publishLocation: 'pipeline'
      artifact: 'api'

- deployment: CD
  dependsOn: CI
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  environment: 'Azure'
  strategy:
    runOnce:
      deploy:
        steps:
        - task: AzureFunctionApp@1
          inputs:
            azureSubscription: '$(azureSubscription)'
            appType: 'functionAppLinux'
            appName: '$(functionAppName)'
            package: '$(Pipeline.Workspace)/api/*.zip'
            runtimeStack: 'DOTNET-ISOLATED|9.0'
