variables:
- group: "Azure"

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - api

pool:
  vmImage: windows-latest

jobs:
- job: CI
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: 'api/src/*.csproj'
      arguments: '--configuration Release --arch x64 --os win --no-self-contained'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: 'api/src/*.csproj'
      nobuild: true
      arguments: '--configuration Release --arch x64 --os win --no-self-contained'
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'api/src/bin/Release/net6.0/win-x64/publish.zip'
      publishLocation: 'pipeline'
      artifact: 'api'

- deployment: CD
  dependsOn: CI
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  environment: 'Azure'
  strategy:
    runOnce:
      deploy:
        steps:
        - task: DownloadPipelineArtifact@2
          inputs:
            buildType: 'current'
            artifactName: 'api'
            targetPath: 'api/src/bin/Release'
        - task: AzureFunctionApp@1
          inputs:
            azureSubscription: '$(azureSubscription)'
            appType: 'functionApp'
            appName: '$(functionAppName)'
            package: '$(System.DefaultWorkingDirectory)/api/src/**/*.zip'
            runtimeStack: 'DOTNET|6.0'
